### ISSUE TITLE
path.existsSync is now called `fs.existsSync`

### ISSUE THREAD

**Issue by ghost** [AGROSICA/node-localize#2]
The above message is printed using node.js 0.8.1

cu
Roman

**Comment by dfellis** [comment]
When I fix this, the library will break for Node 0.2.x and earlier. Do you think I should leave those older deployments behind, or version detect and load the library as appropriate?

**Comment by dfellis** [comment]
I meant 0.4.x and earlier....

**Comment by ghost** [comment]
I see your problem. A simple fix would be something like this:

if (process.versions.node.match(/^0.8..$/) path.existsSync = fs.existsSync;

**Comment by dfellis** [comment]
Hey @rgeber, I figured that the fix should instead make the API usage follow the newest version of Node.js, so if a desired feature in the future makes it difficult/impossible to support the old versions of Node.js, I can just pull out the monkey patching code and still have a working library. 

It's just been published as version 0.4.4, if it works for you, too, then close the issue. Otherwise, let me know.

David

**Comment by dfellis** [comment]
No response for a while. I'm going to assume it's fixed, then.
